#!/bin/bash
echo Building domainfinder...
go build -o bin/domainfinder github.com/musab/domain-name-finder/domainfinder
echo Building synonyms...
go build -o bin/synonyms github.com/musab/domain-name-finder/synonyms
echo Building available...
go build -o bin/available github.com/musab/domain-name-finder/available
echo Building sprinkle...
go build -o bin/sprinkle github.com/musab/domain-name-finder/sprinkle
echo Building coolify...
go build -o bin/coolify github.com/musab/domain-name-finder/coolify
echo Building domainify...
go build -o bin/domainify github.com/musab/domain-name-finder/domainify
echo Done.